### ISSUE TITLE
可以在两段音频中间加一段停顿吗

### ISSUE THREAD

**Issue by EsawaAzusa** [2DIPW/audio_dataset_screener#1]
有的音频多个讲话者不是自动切分容易出错，所以不听到结束不知道是不是单个讲话者的，如果有一秒延迟，此时的操作对应上一段音频，这样就不用一直暂停了。

**Comment by EsawaAzusa** [comment]
另外播放进度条感觉不够精细，对于特别短的音频来说。
（目前正在做动画的语音数据集，经常会有特别短的音频）

**Comment by 2DIPW** [comment]
很好的建议，我去试着做一下

**Comment by 2DIPW** [comment]
建议的功能已添加于v1.2.0，如有bug请另提issue
