### ISSUE TITLE
对大量零散音频文件支持很差

### ISSUE THREAD

**Issue by KamiaoChan** [2DIPW/audio_dataset_screener#2]
在导入大量小音频数据时会直接无响应，总文件有4万个左右，但即使一次只导入3000个文件也会未响应，
希望能设法解决一下这个问题

**Comment by 2DIPW** [comment]
我这里使用4000个测试音频文件一次性导入，进度条会正常走动，最后文件均成功添加，并未出现未响应的情况。鉴于加载进度条是1.2.0版本新加的功能，之前的版本确实会在导入大量文件时假死，请检查是否使用的最新版本。
程序对每个添加的文件都会读取时长并判断是否与列表中已有文件重复，受制于文件系统和C#自身的性能限制，导入文件需要一定的时间。
同时并不建议直接人工筛选如此大量的文件，实在是过于耗费精力，建议先使用其他声纹识别项目粗筛。

**Comment by KamiaoChan** [comment]
确实是需要蛮长时间的等待，只是被进度条是在完成时瞬间从0到100%加之程序占用不明显有些迷惑人，知道有一些开源的声纹识别项目但没能力使用，有一定上手门槛，对于单纯数据集分类有没有相对易用的项目可以推荐？

**Comment by 2DIPW** [comment]
经我这边测试，如果在加载大量文件时什么都不做，进度条可以正常走动；如果这个时候点击过程序窗口，Windows就会判定这是一个未响应的窗口，从而卡死，这确实是由于加载文件的过程阻塞主线程导致的问题，我会在下个版本尝试改为异步加载文件来解决。
关于声纹识别，我个人尝试过的有[这个视频](https://www.bilibili.com/video/BV1sM411i7to)中提到的speechbrain，或[yeyupiaoling/VoiceprintRecognition](https://github.com/yeyupiaoling/VoiceprintRecognition-Pytorch)

**Comment by KamiaoChan** [comment]
的确，在我最初尝试时因怀疑程序未响应是有点击窗口的行为，在4万 8千 3千条数据分别都有过这样的操作，，没有任何介入的情况下3千条是可以导入的只是需要一定时间等待。
对于数据集归类一直都很棘手还是得研究一下声纹粗筛的方法，总的来说还是很感谢作者能制作相应的工具能多一个选择

**Comment by 2DIPW** [comment]
[新版本](https://github.com/2DIPW/audio_dataset_screener/releases/tag/v1.3.0)已经发布，加载文件过程不会再卡死了
此外可以试试我基于yeyupiaoling/VoiceprintRecognition-Pytorch改的声纹识别项目[2DIPW/audio_dataset_vpr](https://github.com/2DIPW/audio_dataset_vpr)

**Comment by KamiaoChan** [comment]
hero！抢沙发拿到星标第一人的位置
